server:
  port: 8080
  servlet:
    context-path: /miNegocioWs
    
spring:
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/minegocio
    username: postgres
    password: postgres
    continueOnError: true